#!/bin/bash
set -o errexit -o nounset -o pipefail

RBD_BIN=%LIBEXEC%/rbd-docker-plugin
CONF=${1:-/etc/docker/rbd-docker-plugin.conf}

ARGS=`cat ${CONF} | \
egrep -v '(^[[:space:]]*#)' | 
awk -F \# '{print $1}' | \
awk -F =  '{
           gsub(/[ \t]/, "", $1);
           gsub(/^[ \t]*/, "", $2);
           gsub(/[ \t]*$/, "", $2);
           printf("-%s=%s ", $1, $2)}'
`
exec ${RBD_BIN} ${ARGS} ${@}
