#!/bin/bash
set -e
set -u

# rbd-docker-plugin postremove

SYSTEMD_SVC=rbd-docker-plugin.service
UPSTART_INIT=/etc/init/rbd-docker-plugin.conf
LOGROTATE_CONF=/etc/logrotate.d/rbd-docker-plugin_logrotate
CRON_JOB=/etc/cron.d/rbd-docker-plugin-checks

# remove cron check
if test -f "$CRON_JOB" ; then
    rm -vf "$CRON_JOB"
fi

# centos 7.x / systemd
if UNIT_DIR=$(pkg-config systemd --variable=systemdsystemunitdir); then
    # stop and disable system service unit
    systemctl stop    ${SYSTEMD_SVC}
    systemctl disable ${SYSTEMD_SVC}
    # unlink the tpkg .service file
    rm -vf "${UNIT_DIR}/${SYSTEMD_SVC}"
else
    # centos 6 / remove the upstart softlink
    if test -L "$UPSTART_INIT" ; then
        stop rbd-docker-plugin
        rm -f "$UPSTART_INIT"
    fi
fi

# remove log config
if test -f "$LOGROTATE_CONF" ; then
    rm -vf "$LOGROTATE_CONF"
fi
